# Remember to set DB_USERNAME, DB_PASSWORD, GOOGLE_API_KEY in application-local.properties
spring:
  config:
    import: classpath:/application-local.properties
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  main:
    allow-bean-definition-overriding: true

google:
  api:
    key: ${GOOGLE_API_KEY}
