# Remember to set DB_USERNAME, DB_PASSWORD, GOOGLE_API_KEY in application-local.properties
spring:
  config:
    import: classpath:/application-local.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/places
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true

google:
  api:
    key: ${GOOGLE_API_KEY}
